routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BeneficiaryController;
use App\Http\Controllers\ReportsController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('index');

Route::middleware(['auth'])->group(function(){
    // CRUD Beneficiarios
    Route::resource('/beneficiario', BeneficiaryController::class);

    //Reportes
    Route::get('/reporte-zona', [ReportsController::class, 'report_consult_zona'])->name('report_consult_zona');
    Route::post('/reporte-zona', [ReportsController::class, 'report_view_zona'])->name('report_view_zona');
});

app/Models/Beneficiary.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Beneficiary extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'full_name',
        'dni',
        'date_of_birth',
        'date_of_issue',
        'address',
        'family_integrants',
        'zone',
        'cell_phone'
    ];

    protected $dates = [
        'date_of_birth',
        'date_of_issue',
        'crated_at'
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/BeneficiaryController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Beneficiary;

class BeneficiaryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $beneficiaries = Beneficiary::orderBy('created_at', 'desc')->get();
        return view('beneficiary.index')->with('beneficiaries', $beneficiaries);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('beneficiary.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $postData = $this->validate($request, [
            'full_name' => 'required',
            'dni' => 'required',
            'date_of_birth' => 'required',
            'date_of_issue' => 'required',
            'address' => 'required',
            'family_integrants' => 'required',
            'zone' => 'required',
            'cell_phone' => 'required'
        ]);

        $benef = Beneficiary::create($postData);

        return redirect()->route('beneficiario.index');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/ReportsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Beneficiary;

class ReportsController extends Controller
{
    public function report_consult_zona()
    {
        return view('reports.zona');
    }

    public function report_view_zona(Request $request)
    {
        $beneficiaries = Beneficiary::where('zone', $request->zone)->get();
        return view('reports.zona')->with('beneficiaries', $beneficiaries);
    }
}

resources/views/beneficiary/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1 class="text-primary">Creación de nuevo beneficiario</h1>

    <form method="POST" action="{{ route('beneficiario.store') }}">
        @csrf

        <div class="mb-3">
          <label for="full_name" class="col-form-label">Nombre completo</label>
          <input type="text" class="form-control @error('full_name') is-invalid @enderror" id="full_name" name="full_name"
            placeholder="Pablito Calvo" value="{{ old('full_name') }}">
          @error('full_name')
            <div class="invalid-feedback">{{ $message }}</div>
          @enderror
        </div>

        <div class="row">
            <div class="col-4">
                <div class="mb-3">
                  <label for="dni" class="col-form-label">DNI</label>
                  <input type="text" class="form-control @error('dni') is-invalid @enderror" id="dni" name="dni"
                    placeholder="25635689" value="{{ old('dni') }}">
                  @error('dni')
                    <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
            </div>
            <div class="col-4">
                <div class="mb-3">
                  <label for="date_of_birth" class="col-form-label">Fecha de nacimiento</label>
                  <input type="date" class="form-control @error('date_of_birth') is-invalid @enderror" id="date_of_birth" name="date_of_birth" value="{{ old('date_of_birth') }}">
                  @error('date_of_birth')
                    <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
            </div>
            <div class="col-4">
                <div class="mb-3">
                  <label for="date_of_issue" class="col-form-label">Fecha de emisión</label>
                  <input type="date" class="form-control @error('date_of_issue') is-invalid @enderror" id="date_of_issue" name="date_of_issue" value="{{ old('date_of_issue') }}">
                  @error('date_of_issue')
                    <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
            </div>
        </div>

        <div class="mb-3">
          <label for="address" class="col-form-label">Dirección</label>
          <input type="text" class="form-control @error('address') is-invalid @enderror" id="address" name="address"
            placeholder="Pablito Calvo" value="{{ old('address') }}">
          @error('address')
            <div class="invalid-feedback">{{ $message }}</div>
          @enderror
        </div>

        <div class="row">
            <div class="col-sm-4">
                <div class="mb-3">
                  <label for="family_integrants" class="col-form-label">N° de familiares</label>
                  <input type="number" class="form-control @error('family_integrants') is-invalid @enderror" id="family_integrants" name="family_integrants"
                    placeholder="5" value="{{ old('family_integrants') }}">
                  @error('family_integrants')
                    <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
            </div>
            <div class="col-sm-4">
                <div class="mb-3">
                  <label for="zone" class="col-form-label">Zona</label>
                  <select class="form-select" name="zone" id="zone" required>
                      <option value="zona1" {{ old('zone') == 'zona1' ? 'selected': '' }}>zona 1</option>
                      <option value="zona2" {{ old('zone') == 'zona2' ? 'selected': '' }}>zona 2</option>
                      <option value="zona3" {{ old('zone') == 'zona3' ? 'selected': '' }}>zona 3</option>
                      <option value="zona4" {{ old('zone') == 'zona4' ? 'selected': '' }}>zona 4</option>
                      <option value="zona5" {{ old('zone') == 'zona5' ? 'selected': '' }}>zona 5</option>
                  </select>
                  @error('zone')
                    <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
            </div>
            <div class="col-sm-4">
                <div class="mb-3">
                  <label for="cell_phone" class="col-form-label">N° telefónco</label>
                  <input type="text" class="form-control @error('cell_phone') is-invalid @enderror" id="cell_phone" name="cell_phone"
                    placeholder="964563256" value="{{ old('cell_phone') }}">
                  @error('cell_phone')
                    <div class="invalid-feedback">{{ $message }}</div>
                  @enderror
                </div>
            </div>
        </div>

        <div class="col-auto mt-3">
            <button type="submit" class="btn btn-primary mb-3">Registrar</button>
            <a class="btn btn-default mb-3" href="{{ route('beneficiario.index') }}">Cancelar</a>
        </div>
    </form>
</div>
@endsection

resources/views/beneficiary/index.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
    <h1>Lista de beneficiarios registrados</h1>

    <table class="table">
        <thead class="table-dark">
            <tr>
                <th>Nombre completo</th>
                <th>DNI</th>
                <th>Fecha de nacimiento</th>
                <th>Fecha de emisión</th>
                <th>Fecha de registro</th>
                <th>Dirección</th>
                <th>N° familiares</th>
                <th>Zona</th>
                <th>Teléfono</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($beneficiaries as $beneficiary)
            <tr>
                <td>{{ $beneficiary->full_name }}</td>
                <td>{{ $beneficiary->dni }}</td>
                <td>{{ $beneficiary->date_of_birth->format('d-m-Y') }}</td>
                <td>{{ $beneficiary->date_of_issue->format('d-m-Y') }}</td>
                <td>{{ $beneficiary->created_at->format('d-m-Y') }}</td>
                <td>{{ $beneficiary->address }}</td>
                <td>{{ $beneficiary->family_integrants }}</td>
                <td>{{ $beneficiary->zone }}</td>
                <td>{{ $beneficiary->cell_phone }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Dashboard') }}</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    {{ __('You are logged in!') }}
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav me-auto">
                        @auth
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="beneficieries" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Beneficiarios
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="beneficieries">
                                    <li><a class="dropdown-item" href="{{ route('beneficiario.create') }}">Nuevo</a></li>
                                    <li><a class="dropdown-item" href="{{ route('beneficiario.index') }}">Listar</a></li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="reports" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    Reportes
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="reports">
                                    <li><a class="dropdown-item" href="{{ route('report_view_zona') }}">Por zona</a></li>
                                </ul>
                            </li>
                        @endauth
                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ms-auto">
                        <!-- Authentication Links -->
                        @guest
                            @if (Route::has('login'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                                </li>
                            @endif

                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/reports/zona.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <form method="POST" class="mb-3" action="{{ route('report_view_zona') }}">
            @csrf

            <div class="row">
                <div class="col-sm-6">
                    <select class="form-select" name="zone" id="zone" required>
                        <option value="zona1" {{ old('zone') == 'zona1' ? 'selected': '' }}>zona 1</option>
                        <option value="zona2" {{ old('zone') == 'zona2' ? 'selected': '' }}>zona 2</option>
                        <option value="zona3" {{ old('zone') == 'zona3' ? 'selected': '' }}>zona 3</option>
                        <option value="zona4" {{ old('zone') == 'zona4' ? 'selected': '' }}>zona 4</option>
                        <option value="zona5" {{ old('zone') == 'zona5' ? 'selected': '' }}>zona 5</option>
                    </select>
                      @error('zone')
                        <div class="invalid-feedback">{{ $message }}</div>
                      @enderror
                </div>
                <div class="col-sm-4">
                    <button type="submit" class="btn btn-primary mb-3">Consultar</button>
                </div>
            </div>
        </form>

        @isset($beneficiaries)

            <table class="table">
                <thead class="table-dark">
                    <tr>
                        <th>Nombre completo</th>
                        <th>DNI</th>
                        <th>Fecha de nacimiento</th>
                        <th>Fecha de emisión</th>
                        <th>Fecha de registro</th>
                        <th>Dirección</th>
                        <th>N° familiares</th>
                        <th>Zona</th>
                        <th>Teléfono</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach ($beneficiaries as $beneficiary)
                    <tr>
                        <td>{{ $beneficiary->full_name }}</td>
                        <td>{{ $beneficiary->dni }}</td>
                        <td>{{ $beneficiary->date_of_birth->format('d-m-Y') }}</td>
                        <td>{{ $beneficiary->date_of_issue->format('d-m-Y') }}</td>
                        <td>{{ $beneficiary->created_at->format('d-m-Y') }}</td>
                        <td>{{ $beneficiary->address }}</td>
                        <td>{{ $beneficiary->family_integrants }}</td>
                        <td>{{ $beneficiary->zone }}</td>
                        <td>{{ $beneficiary->cell_phone }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @endisset

    </div>
@endsection